### ISSUE TITLE
TypeError: in method 'SystemSettings_GetColour', expected argument 1 of type 'wxSystemColour'

### ISSUE THREAD

**Issue by dutch-rob** [manns/pyspread#121]
I am trying to have a better look at pyspread. I could install and run it on Linux Mint 17.2 but noticed that I got an old version of pyspread; I believe it was 0.2.3. So I downloaded the source for 0.4.1, ran setup but then I get the following error when I try to run:
```
TypeError: in method 'SystemSettings_GetColour', expected argument 1 of type 'wxSystemColour'
```
I am copying the trace back below

Do you have advice on how I can resolve this?

Thanks, Rob

```
/usr/bin/python2.7 /usr/local/lib/python2.7/dist-packages/pyspread/src/pyspread.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyspread/src/pyspread.py", line 243, in <module>
    pyspread()
  File "/usr/local/lib/python2.7/dist-packages/pyspread/src/pyspread.py", line 229, in pyspread
    app = MainApplication(S=S, redirect=False)
  File "/usr/local/lib/python2.7/dist-packages/pyspread/src/pyspread.py", line 172, in __init__
    wx.App.__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7981, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7555, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyspread/src/pyspread.py", line 191, in OnInit
    from src.gui._main_window import MainWindow
  File "/usr/local/lib/python2.7/dist-packages/pyspread/src/../src/gui/_main_window.py", line 72, in <module>
    from _grid import Grid
  File "/usr/local/lib/python2.7/dist-packages/pyspread/src/../src/gui/_grid.py", line 44, in <module>
    from _grid_renderer import GridRenderer
  File "/usr/local/lib/python2.7/dist-packages/pyspread/src/../src/gui/_grid_renderer.py", line 45, in <module>
    class GridRenderer(wx.grid.PyGridCellRenderer):
  File "/usr/local/lib/python2.7/dist-packages/pyspread/src/../src/gui/_grid_renderer.py", line 49, in GridRenderer
    tuple([c / 255.0 for c in get_color(config["selection_color"]).Get()]
  File "/usr/local/lib/python2.7/dist-packages/pyspread/src/../src/sysvars.py", line 82, in get_color
    return wx.SystemSettings.GetColour(name)
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_misc.py", line 159, in GetColour
    return _misc_.SystemSettings_GetColour(*args, **kwargs)
TypeError: in method 'SystemSettings_GetColour', expected argument 1 of type 'wxSystemColour'

Process finished with exit code 1
```

**Comment by manns** [comment]
On Wed, 07 Oct 2015 17:17:18 -0700
Rob <notifications@github.com> wrote:

> I am trying to have a better look at pyspread. I could install and
> run it on Linux Mint 17.2 but noticed that I got an old version of
> pyspread; I believe it was 0.2.3. So I downloaded the source for
> 0.4.1, ran setup but then I get the following error when I try to
> run: ``` TypeError: in method 'SystemSettings_GetColour', expected
> argument 1 of type 'wxSystemColour' ``` I am copying the trace back
> below
> 
> Do you have advice on how I can resolve this?

Dear Rob

Please remove your ~/.pyspreadrc file and try again.

Kind Regards

Martin

**Comment by dutch-rob** [comment]
Dear Martin,

Yes, that worked. Great, thanks very much!

Best regards,
Rob
