### ISSUE TITLE
ValueError  in gpg when saving

### ISSUE THREAD

**Issue by mgunyho** [manns/pyspread#147]
When saving a spreadsheet, I get
```
Traceback (most recent call last):
  File "pyspread/pyspread/src/actions/_grid_actions.py", line 638, in save
    self._save_sign(filepath)
  File "pyspread/pyspread/src/actions/_grid_actions.py", line 599, in _save_s
    self.sign_file(filepath)
  File "pyspread/src/actions/_grid_actions.py", line 429, in sign_fi
    signed_data = sign(filepath)
  File "pyspread/src/lib/gpg.py", line 230, in sign
    raise ValueError(msg.format(config["gpg_key_fingerprint"]))
ValueError: No private key for fingerprint .
```
The GUI freezes when this happens but files are saved, although they are marked as non-approved when opening them again.

IMO, catching this exception should open a warning dialog that the file will be marked as unsafe or something along those lines. Or am I missing a dependency?

**Comment by manns** [comment]
No this was clearly a regression.
