### ISSUE TITLE
Windows version hangs on save

### ISSUE THREAD

**Issue by nidingen** [manns/pyspread#151]
I have pyspread installed on Windows 10, using the installer. The version is 1.0.2.

pyspread hangs on save, not completely, one can still browse and use the menus, but not work in any of the cells. After quit is selected (since the menu works) one can save and exit. But upon restart the spreadsheet does not work anymore, all cell content is treated as text, no interpretation at all takes place.

**Comment by manns** [comment]
Thank you for creating this issue.
I have never tested pyspread against Windows 10.

The behaviour sounds like pyspread does not get permissions to write.
Starting pyspread from the cmd and reporting the errors would help a lot.

If the spreadsheet does not work on restart, something bad is happening in the registry.
Please remove the pyspread keys and start again.

While I have access to a Windows 10 PC, I will not find time for testing until end of this month. For earlier fixes, I would need more detailed error logs.

**Comment by nidingen** [comment]
This is the output from cmd window:

C:\Program Files (x86)\pyspread\library.zip\src\lib\_grid_cairo_renderer.py:693: PangoWarning: couldn't load font "MS 
Shell Dlg 2 Not-Rotated 10", falling back to "Sans Not-Rotated 10", expect ugly output.
Traceback (most recent call last):
  File "C:\Program Files (x86)\pyspread\library.zip\src\actions\_grid_actions.py", line 611, in save
  File "C:\Program Files (x86)\pyspread\library.zip\src\actions\_grid_actions.py", line 577, in _save_sign
  File "C:\Program Files (x86)\pyspread\library.zip\src\actions\_grid_actions.py", line 407, in sign_file
  File "C:\Program Files (x86)\pyspread\library.zip\src\lib\gpg.py", line 223, in sign
  File "gnupg.pyo", line 532, in __init__
ValueError: Error invoking gpg: 1: 'gpg' is not recognized as an internal or external command,
operable program or batch file.

Note that pyspread does work on restart, but not the file that one tried to save. If one starts with a new, blank file, 
everything works ok (except that the save possibility is quite essential...).

 -------Original Message-------

**Comment by manns** [comment]
Have you installed GPG4Win (https://www.gpg4win.org/)?
It is a prerequisite.

**Comment by nidingen** [comment]
Hi,

no, I had not, becuase the instructions regarding the installer mentioned nothing about manual install packages being 
necessary when using the installer.

Nonetheless, I did install per the suggested link, created a new PGP key, and tried to save a file.

I suspect something is wrong when creating the PGP key. This is the traceback (before trying to save a file):

Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Program Files (x86)\pyspread\library.zip\threading.py", line 810, in __bootstrap_inner
  File "C:\Program Files (x86)\pyspread\library.zip\threading.py", line 763, in run
  File "gnupg.pyo", line 571, in _read_response
  File "C:\Program Files (x86)\pyspread\library.zip\codecs.py", line 533, in readline
  File "C:\Program Files (x86)\pyspread\library.zip\codecs.py", line 480, in read
UnicodeDecodeError: 'utf8' codec can't decode byte 0x84 in position 4: invalid start byte



 -------Original Message-------

**Comment by manns** [comment]
OK, I only mention it on the Web-Site (see https://manns.github.io/pyspread/download.html)
I will try to integrate it into the next installer.

Regarding the error, I have difficulties reproducing it.
Please check that you have selected the GPG key in File --> Switch GPG key.
Also check if the key is really present in your GPG keyring.
Finally, please let me know if there are any special characters in your file.

**Comment by manns** [comment]
I have worked on a new Windows release.
The issue seems to result from an API change in GPG4Win.
Until this is fixed, installing GPG4Win version 2.2.6 may solve the issue.

**Comment by manns** [comment]
According to the gnupg devs, this seems to be a python-gnupg issue.

**Comment by manns** [comment]
I now have a second report on a similar issue on Windows 10.
It seems that on some Windows 10 systems, pyspread works and on some it does not.
Should you encounter further error messages when starting pyspread via the cmd please let me know.

**Comment by vovkkk** [comment]
Can be this gpg stuff just disabled? it is a pure annoyance, esp. that I use only my own spreadsheets

Switch gpg key:

```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "threading.pyo", line 763, in run
  File "gnupg.pyo", line 753, in _read_response
  File "gnupg.pyo", line 616, in handle_status
ValueError: Unknown status message: u'KEY_CONSIDERED'

Exception in thread Thread-13:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "threading.pyo", line 763, in run
  File "gnupg.pyo", line 753, in _read_response
  File "gnupg.pyo", line 616, in handle_status
ValueError: Unknown status message: u'KEY_CONSIDERED'

Exception in thread Thread-20:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "threading.pyo", line 763, in run
  File "gnupg.pyo", line 753, in _read_response
  File "gnupg.pyo", line 616, in handle_status
ValueError: Unknown status message: u'KEY_CONSIDERED'

Exception in thread Thread-25:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "threading.pyo", line 763, in run
  File "gnupg.pyo", line 753, in _read_response
  File "gnupg.pyo", line 616, in handle_status
ValueError: Unknown status message: u'KEY_CONSIDERED'

Exception in thread Thread-28:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "threading.pyo", line 763, in run
  File "gnupg.pyo", line 736, in _read_response
  File "codecs.pyo", line 533, in readline
  File "codecs.pyo", line 480, in read
UnicodeDecodeError: 'utf8' codec can't decode byte 0x82 in position 5: invalid start byte
```

Saving:

```
Traceback (most recent call last):
  File "src\gui\_widgets.pyo", line 1070, in OnMessage
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcf in position 11: invalid continuation byte
```

**Comment by manns** [comment]
On Linux, pyspread now works without python-gnupg installed.
Please try out the fix. If present you need to remove python gnupg for the changes to come into effect..

**Comment by vitesse-ftian** [comment]
I run into same bug on Linux Ubuntu 1804, python 2 version (1.1.1).
